// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"iot-alert-center/internal/cache"
	"iot-alert-center/internal/client/kafka"
	"iot-alert-center/internal/client/mqtt"
	"iot-alert-center/internal/client/resty"
	"iot-alert-center/internal/handler"
	"iot-alert-center/internal/job"
	"iot-alert-center/internal/repository"
	"iot-alert-center/internal/server"
	"iot-alert-center/internal/service"
	"iot-alert-center/pkg/app"
	"iot-alert-center/pkg/eventbus"
	"iot-alert-center/pkg/jwt"
	"iot-alert-center/pkg/log"
	"iot-alert-center/pkg/server/http"
	"iot-alert-center/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger, eventBus *eventbus.EventBus) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	db := repository.NewDB(viperViper, logger)
	handlerHandler := handler.NewHandler(logger)
	client := repository.NewRedis(viperViper)
	repositoryRepository := repository.NewRepository(logger, db, client)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT, eventBus)
	sysPostRepository := repository.NewSysPostRepository(repositoryRepository)
	sysPostService := service.NewSysPostService(serviceService, sysPostRepository)
	sysPostHandler := handler.NewSysPostHandler(handlerHandler, sysPostService)
	sysDeptRepository := repository.NewSysDeptRepository(db)
	sysDeptService := service.NewSysDeptService(sysDeptRepository)
	sysDeptHandler := handler.NewSysDeptHandler(sysDeptService, db)
	sysMenuRepository := repository.NewSysMenuRepository(db)
	sysApiRepository := repository.NewSysApiRepository(repositoryRepository)
	sysMenuService := service.NewSysMenuService(sysMenuRepository, sysApiRepository)
	sysMenuHandler := handler.NewSysMenuHandler(sysMenuService)
	sysRoleRepository := repository.NewSysRoleRepository(db)
	sysRoleDeptRepository := repository.NewSysRoleDeptRepository(db)
	sysRoleMenuRepository := repository.NewSysRoleMenuRepository(db)
	sysRoleService := service.NewSysRoleService(db, sysRoleRepository, sysRoleDeptRepository, sysRoleMenuRepository)
	sysRoleHandler := handler.NewSysRoleHandler(sysRoleService, db)
	sysUserRepository := repository.NewSysUserRepository(db)
	sysUserRoleRepository := repository.NewSysUserRoleRepository(db)
	sysUserPostRepository := repository.NewSysUserPostRepository(db)
	sysLogininforRepository := repository.NewSysLogininforRepository(db)
	sysLogininforService := service.NewSysLogininforService(sysLogininforRepository)
	userCache := cache.NewUserCache(client)
	sysUserService := service.NewSysUserService(db, viperViper, sysUserRepository, sysUserRoleRepository, sysUserPostRepository, sysDeptRepository, sysRoleRepository, sysPostRepository, sysRoleMenuRepository, sysLogininforService, sysRoleService, sysRoleDeptRepository, userCache)
	sysUserHandler := handler.NewSysUserHandler(sysUserService)
	sysLogininforHandler := handler.NewSysLogininforHandler(sysLogininforService)
	sysApiService := service.NewSysApiService(sysApiRepository)
	sysApiHandler := handler.NewSysApiHandler(handlerHandler, sysApiService)
	sysDictTypeRepository := repository.NewSysDictTypeRepository(repositoryRepository)
	sysDictTypeService := service.NewSysDictTypeService(serviceService, sysDictTypeRepository)
	sysDictTypeHandler := handler.NewSysDictTypeHandler(handlerHandler, sysDictTypeService)
	sysDictDataRepository := repository.NewSysDictDataRepository(repositoryRepository)
	sysDictDataService := service.NewSysDictDataService(serviceService, sysDictDataRepository)
	sysDictDataHandler := handler.NewSysDictDataHandler(handlerHandler, sysDictDataService)
	sysOperLogRepository := repository.NewSysOperLogRepository(repositoryRepository)
	sysOperLogService := service.NewSysOperLogService(serviceService, sysOperLogRepository)
	sysOperLogHandler := handler.NewSysOperLogHandler(handlerHandler, sysOperLogService)
	vsLLMProviderRepository := repository.NewVsLLMProviderRepository(repositoryRepository)
	vsLLMProviderService := service.NewVsLLMProviderService(serviceService, vsLLMProviderRepository)
	vsLLMProviderHandler := handler.NewVsLLMProviderHandler(handlerHandler, vsLLMProviderService)
	vsTTSProviderRepository := repository.NewVsTTSProviderRepository(repositoryRepository)
	vsTTSProviderService := service.NewVsTTSProviderService(serviceService, vsTTSProviderRepository)
	vsTTSProviderHandler := handler.NewVsTTSProviderHandler(handlerHandler, vsTTSProviderService)
	vsPromptTemplateRepository := repository.NewVsPromptTemplateRepository(repositoryRepository)
	vsPromptTemplateService := service.NewVsPromptTemplateService(serviceService, vsPromptTemplateRepository)
	vsPromptTemplateHandler := handler.NewVsPromptTemplateHandler(handlerHandler, vsPromptTemplateService)
	vsWorkspaceRepository := repository.NewVsWorkspaceRepository(repositoryRepository)
	vsWorkspaceService := service.NewVsWorkspaceService(serviceService, vsWorkspaceRepository)
	vsWorkspaceHandler := handler.NewVsWorkspaceHandler(handlerHandler, vsWorkspaceService)
	vsProjectRepository := repository.NewVsProjectRepository(repositoryRepository)
	vsProjectService := service.NewVsProjectService(serviceService, vsProjectRepository)
	vsProjectHandler := handler.NewVsProjectHandler(handlerHandler, vsProjectService)
	vsChapterRepository := repository.NewVsChapterRepository(repositoryRepository)
	vsChapterService := service.NewVsChapterService(serviceService, vsChapterRepository)
	vsChapterHandler := handler.NewVsChapterHandler(handlerHandler, vsChapterService)
	vsScriptSegmentRepository := repository.NewVsScriptSegmentRepository(repositoryRepository)
	vsAudioClipRepository := repository.NewVsAudioClipRepository(repositoryRepository)
	vsScriptSegmentService := service.NewVsScriptSegmentService(serviceService, vsScriptSegmentRepository, vsAudioClipRepository)
	vsScriptSegmentHandler := handler.NewVsScriptSegmentHandler(handlerHandler, vsScriptSegmentService)
	vsCharacterRepository := repository.NewVsCharacterRepository(repositoryRepository)
	vsCharacterService := service.NewVsCharacterService(serviceService, vsCharacterRepository)
	vsCharacterHandler := handler.NewVsCharacterHandler(handlerHandler, vsCharacterService)
	vsFileImportService := service.NewVsFileImportService(serviceService, vsProjectRepository, vsChapterRepository)
	vsFileImportHandler := handler.NewVsFileImportHandler(handlerHandler, vsFileImportService)
	vsLLMLogRepository := repository.NewVsLLMLogRepository(repositoryRepository)
	vsLLMLogService := service.NewVsLLMLogService(serviceService, vsLLMLogRepository)
	vsLLMLogHandler := handler.NewVsLLMLogHandler(handlerHandler, vsLLMLogService)
	vsVoiceProfileRepository := repository.NewVsVoiceProfileRepository(repositoryRepository)
	vsVoiceProfileService := service.NewVsVoiceProfileService(serviceService, vsVoiceProfileRepository)
	vsVoiceProfileHandler := handler.NewVsVoiceProfileHandler(handlerHandler, vsVoiceProfileService)
	vsPronunciationDictRepository := repository.NewVsPronunciationDictRepository(repositoryRepository)
	vsPronunciationDictService := service.NewVsPronunciationDictService(serviceService, vsPronunciationDictRepository)
	vsPronunciationDictHandler := handler.NewVsPronunciationDictHandler(handlerHandler, vsPronunciationDictService)
	vsPreciseFillService := service.NewVsPreciseFillService(serviceService, vsChapterRepository, vsScriptSegmentRepository)
	vsPreciseFillHandler := handler.NewVsPreciseFillHandler(handlerHandler, vsPreciseFillService)
	vsSceneRepository := repository.NewVsSceneRepository(repositoryRepository)
	vsChapterSplitService := service.NewVsChapterSplitService(serviceService, db, vsChapterRepository, vsProjectRepository, vsPromptTemplateRepository, vsLLMProviderRepository, vsSceneRepository, vsScriptSegmentRepository, vsCharacterRepository, vsLLMLogRepository)
	vsChapterSplitHandler := handler.NewVsChapterSplitHandler(handlerHandler, vsChapterSplitService)
	vsCharacterExtractService := service.NewVsCharacterExtractService(serviceService, vsProjectRepository, vsChapterRepository, vsCharacterRepository, vsPromptTemplateRepository, vsLLMProviderRepository, vsLLMLogRepository)
	vsCharacterExtractHandler := handler.NewVsCharacterExtractHandler(handlerHandler, vsCharacterExtractService)
	vsVoiceEmotionRepository := repository.NewVsVoiceEmotionRepository(repositoryRepository)
	vsVoiceEmotionService := service.NewVsVoiceEmotionService(serviceService, vsVoiceEmotionRepository)
	vsVoiceEmotionHandler := handler.NewVsVoiceEmotionHandler(handlerHandler, vsVoiceEmotionService)
	vsTTSSynthesizeService := service.NewVsTTSSynthesizeService(serviceService, vsScriptSegmentRepository, vsCharacterRepository, vsVoiceProfileRepository, vsVoiceEmotionRepository, vsPronunciationDictRepository, vsAudioClipRepository, vsTTSProviderRepository, vsProjectRepository)
	vsTTSSynthesizeHandler := handler.NewVsTTSSynthesizeHandler(handlerHandler, vsTTSSynthesizeService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, db, sysPostHandler, sysDeptHandler, sysMenuHandler, sysRoleHandler, sysUserHandler, eventBus, sysLogininforHandler, userCache, sysApiHandler, sysDictTypeHandler, sysDictDataHandler, sysOperLogHandler, sysOperLogService, vsLLMProviderHandler, vsTTSProviderHandler, vsPromptTemplateHandler, vsWorkspaceHandler, vsProjectHandler, vsChapterHandler, vsScriptSegmentHandler, vsCharacterHandler, vsFileImportHandler, vsLLMLogHandler, vsVoiceProfileHandler, vsPronunciationDictHandler, vsPreciseFillHandler, vsChapterSplitHandler, vsCharacterExtractHandler, vsVoiceEmotionHandler, vsTTSSynthesizeHandler)
	jobJob := job.NewJob(transaction, logger, sidSid, viperViper)
	userJob := job.NewUserJob(jobJob)
	jobServer := server.NewJobServer(logger, viperViper, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewTransaction, repository.NewSysPostRepository, repository.NewSysDeptRepository, repository.NewSysMenuRepository, repository.NewSysRoleRepository, repository.NewSysRoleDeptRepository, repository.NewSysRoleMenuRepository, repository.NewSysUserRoleRepository, repository.NewSysUserPostRepository, repository.NewSysUserRepository, repository.NewSysLogininforRepository, repository.NewSysApiRepository, repository.NewSysDictTypeRepository, repository.NewSysDictDataRepository, repository.NewSysOperLogRepository, repository.NewVsLLMProviderRepository, repository.NewVsTTSProviderRepository, repository.NewVsPromptTemplateRepository, repository.NewVsWorkspaceRepository, repository.NewVsProjectRepository, repository.NewVsChapterRepository, repository.NewVsScriptSegmentRepository, repository.NewVsCharacterRepository, repository.NewVsLLMLogRepository, repository.NewVsVoiceProfileRepository, repository.NewVsPronunciationDictRepository, repository.NewVsSceneRepository, repository.NewVsAudioClipRepository, repository.NewVsVoiceEmotionRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewSysPostService, service.NewSysDeptService, service.NewSysMenuService, service.NewSysRoleService, service.NewSysUserService, service.NewSysLogininforService, service.NewSysApiService, service.NewSysDictTypeService, service.NewSysDictDataService, service.NewSysOperLogService, service.NewVsLLMProviderService, service.NewVsTTSProviderService, service.NewVsPromptTemplateService, service.NewVsWorkspaceService, service.NewVsProjectService, service.NewVsChapterService, service.NewVsScriptSegmentService, service.NewVsCharacterService, service.NewVsFileImportService, service.NewVsLLMLogService, service.NewVsVoiceProfileService, service.NewVsPronunciationDictService, service.NewVsPreciseFillService, service.NewVsChapterSplitService, service.NewVsCharacterExtractService, service.NewVsVoiceEmotionService, service.NewVsTTSSynthesizeService, cache.NewUserCache, mqtt.NewMqttClient, kafka.NewKafkaProducer, resty.NewRestyClient)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewSysPostHandler, handler.NewSysDeptHandler, handler.NewSysMenuHandler, handler.NewSysRoleHandler, handler.NewSysUserHandler, handler.NewSysLogininforHandler, handler.NewSysApiHandler, handler.NewSysDictTypeHandler, handler.NewSysDictDataHandler, handler.NewSysOperLogHandler, handler.NewVsLLMProviderHandler, handler.NewVsTTSProviderHandler, handler.NewVsPromptTemplateHandler, handler.NewVsWorkspaceHandler, handler.NewVsProjectHandler, handler.NewVsChapterHandler, handler.NewVsScriptSegmentHandler, handler.NewVsCharacterHandler, handler.NewVsFileImportHandler, handler.NewVsLLMLogHandler, handler.NewVsVoiceProfileHandler, handler.NewVsPronunciationDictHandler, handler.NewVsPreciseFillHandler, handler.NewVsChapterSplitHandler, handler.NewVsCharacterExtractHandler, handler.NewVsVoiceEmotionHandler, handler.NewVsTTSSynthesizeHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(
		httpServer,
		jobServer,
	), app.WithName("gin-vue3-admin"),
	)
}
