env: prod
http:
  host: 0.0.0.0
  port: 5000
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  db:
    user:
      driver: postgres
      dsn: host=vostory-postgres user=vostory password=vostory123456 dbname=vostory port=5432 sslmode=disable TimeZone=Asia/Shanghai
  redis:
    addr: vostory-redis:6379
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_level: info
  encoding: json
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
